```{r num3, include=FALSE}

set.seed(123)
N = 12
df = data.frame(ID = paste0(rep(1:N)),
                 Stunden = round(rnorm(N, 10, 4))
                  )

df2 = df
df = as.data.frame(t(df))
colnames(df) = NULL
#kable(df[,], col.names = NULL)
table = df %>%
  kbl() %>%
  kable_styling()

```


Question
======== 

In der folgenden Tabelle sehen Sie die wöchentliche Fernsehzeit in Stunden von 12 Schülern.

```{r num4}
table
```

Welche Aussagen zu dieser Tabelle sind zutreffend? 


Answerlist
----------

* Der Median beträgt `r median(df2$Stunden)`
* Der Median beträgt `r median(df2$Stunden) + 0.5`
* Das untere Quartil beträgt 8
* Das obere Quartil beträgt 15
* Der Interquartilabstand beträgt 5,5

Solution
========

Answerlist
----------

* Richtig. 
$$q_{0.5} = \frac{x_{(I_{0.5})} + x_{(I_{0.5}+1)}}{2} = \frac{x_{(6)} + x_{(7)}}{2} = \frac{10 + 11}{2} = 10.5$$
* Falsch. Siehe hierzu Formel zur Berechnung des Medians / Formel zur Berechnung der Quartile 
* Richtig.
$$q_{0.25} = \frac{x_{(I_{0.25})} + x_{(I_{0.25}+1)}}{2} = \frac{x_{(3)} + x_{(4)}}{2} = \frac{8 + 8}{2} = 8$$
* Falsch.
$$q_{0.75} = \frac{x_{(I_{0.75})} + x_{(I_{0.75}+1)}}{2} = \frac{x_{(9)} + x_{(10)}}{2} = \frac{12 + 15}{2} = 13.5$$
* Richtig.
$$q_{A}= \widetilde{x}_{0.75} - \widetilde{x}_{0.25} = 13.5 - 8 =  5.5$$

Meta-information
================
exname: Num1
extype: mchoice 
exsolution: 10101
exshuffle: TRUE


