```{r data generation, echo = FALSE, results = "hide"}
## DATA GENERATION
n <- sample(35:65,1)
mx <- runif(1, 40, 60)
my <- runif(1, 200, 280)
sx <- runif(1, 9, 12)
sy <- runif(1, 44, 50)
r <- round(runif(1, 0.5, 0.9), 2)
x <- rnorm(n, mx, sd = sx)
y <- (r * x/sx + rnorm(n, my/sy - r * mx/sx, sqrt(1 - r^2))) * sy

mx <- round(mean(x))
my <- round(mean(y))
r <- round(cor(x, y), digits = 2)
varx <- round(var(x))
vary <- round(var(y))

b <- r * sqrt(vary/varx)
a <- my - b * mx

X <- round(runif(1, -10, 10) + mx)

## QUESTION/ANSWER GENERATION
sol <- round(a + b * X, 2)
```

Question
========

Für `r n` Firmen wurden die Anzahl der Mitarbeiter $X$ und der Betrag der Ausgaben für die Weiterbildung $Y$ (in EUR) erfasst. Die relevanten Deskriptivstatistiken für die beiden Variablen lauten:

|          | Variable $X$ | Variable $Y$ |
|:--------:|:------------:|:------------:|
| Mean     | `r mx`       | `r my`       |
| Variance | `r varx`     | `r vary`     |

<br>

Die Korrelation zwischen $X$ und $Y$ beträgt `r r`.

Schätzen Sie den erwarteten Betrag, den eine Firma mit `r X` Mitarbeitern für die Weiterbildung ausgibt, mithilfe der Methode der kleinsten Quadrate. Runden Sie das Ergebnis auf 2 Nachkommastellen. 


Solution
========

Zunächst wird die Regressionsgerade $y_i = a + \beta x_i +
\varepsilon_i$ bestimmt. Die Regressionskoeffizienten sind gegeben durch:
\begin{eqnarray*}
&& \hat \beta = r \cdot \frac{s_y}{s_x} = 
`r r` \cdot \sqrt{\frac{`r vary`}{`r varx`}} = `r round(b,3)`, \\
&& \hat a = \bar y - \hat \beta \cdot \bar x = 
`r my` - `r round(b,3)` \cdot `r mx` = `r round(a,3)`.
\end{eqnarray*}

Der geschätzte Betrag, den eine Firma mit
`r X` Mitarbeitern für die Weiterbildung ausgibt, beträgt:
\begin{eqnarray*}
\hat y = `r round(a, 3)` + `r round(b, 3)` \cdot `r X` = `r sol`.
\end{eqnarray*}


Meta-information
================
extype: num
exsolution: `r fmt(sol, 2)`
exname: Prediction
extol: 0.01