```{r num3, include=FALSE}

set.seed(123)
N = 10
df = data.frame(ID = paste0(rep(1:N)),
                 Messwerte = round(rnorm(N, 106, 10.1))
                  )

df2 = df
df = as.data.frame(t(df))
colnames(df) = NULL
#kable(df[,], col.names = NULL)
table = df %>%
  kbl() %>%
  kable_styling()

result = t.test(df2$Messwerte, mu = 100)


```


Question 
======== 

Sie haben Werte folgender Stichprobe erhoben: 

```{r echo=FALSE}
table
```

Unterscheidet sich dieser Gruppenmittelwert bei α = .05 signifikant vom Populationsdurchschnitt? (μ = 100)

Answerlist
----------

* Es besteht kein signifikanter Unterschied mit t(emp) = `r round(result$statistic,3)` und t(krit) = `r round(qt(0.975, 9),3) `
* Es besteht ein signifikanter Unterschied mit t(emp) = `r round(result$statistic,3)` und t(krit) = `r round(qt(0.95, 9),3) `
* Es besteht kein signifikanter Unterschied mit t(emp) = `r round(result$statistic,3)` und t(krit) = `r round(qt(0.975, 10),3) `
* Es besteht kein signifikanter Unterschied mit t(emp) = `r round(result$statistic,3)` und t(krit) = `r round(qt(0.975, 8),3) `
* Es besteht ein signifikanter Unterschied mit t(emp) = `r round(result$statistic,3)` und t(krit) = `r round(qt(0.95, 8),3) `

Solution
========

Answerlist
----------

* Richtig.
* Falsch.
* Falsch.
* Falsch.
* Falsch.

Meta-information
================
exname: t-test
extype: mchoice 
exsolution: 10000
exshuffle: TRUE
